// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torpedo.Repositories;

#nullable disable

namespace Torpedo.Migrations
{
    [DbContext(typeof(ResultContext))]
    [Migration("20220604094705_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Torpedo.Model.Result", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ElsoJatekosNeve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElsoJatekosTalalata")
                        .HasColumnType("int");

                    b.Property<int>("KorokSzama")
                        .HasColumnType("int");

                    b.Property<string>("MasodikJatekosNeve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasodikJatekosTalalata")
                        .HasColumnType("int");

                    b.Property<string>("Nyertes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eredmenyek");
                });
#pragma warning restore 612, 618
        }
    }
}
